/*
 * FluxVault - A universal transport protocol for Hytale.
 * Copyright (c) 2026 Ben (popo70023)
 * Licensed under the MIT License.
 */
package io.github.popo70023.fluxvault.api;

import com.hypixel.hytale.protocol.BlockFace;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * The universal capability bridge for objects capable of participating in the Flux logistics network.
 * <p>
 * Implemented by Blocks, Entities, or Components to expose their routing and storage capabilities.
 * A single provider (e.g., an advanced machine) can multiplex multiple handlers (e.g., accepting both Liquid and Energy),
 * and can dynamically route capabilities based on the physical face being accessed.
 * </p>
 */
public interface IFluxHandlerProvider {

    /**
     * Retrieves the authoritative handler for a specific Flux resource type, routed by the accessed block face.
     * <p>
     * <b>LIFECYCLE WARNING:</b> The returned handler represents the current logical state of the provider.
     * Callers should NEVER cache the returned {@code IFluxHandler} long-term across multiple ticks,
     * as the provider's capabilities may dynamically change (e.g., a machine component being uninstalled).
     * </p>
     *
     * @param type     The architectural type of the resource requested (e.g., {@link FluxType#LIQUID}).
     * @param face     The physical direction/face from which the provider is being accessed (e.g., {@link BlockFace#Up}).
     *                 Must be {@link BlockFace#None} if the access is internal or dimensionless,
     *                 or requesting the global/default handler. STRICTLY NON-NULL.
     * @param slotName An optional specific slot identifier (e.g., "water_in") to target a named container,
     *                 or {@code null} to query the default un-filtered handler.
     * @param access   The intended operation (FILL or DRAIN) the caller wishes to perform.
     *                 Used to evaluate physical compatibility before a connection is established
     *                 (e.g., an output-only face returning null for a FILL request to prevent pipe connection).
     *                 STRICTLY NON-NULL.
     * @param <F>      The carrier payload type.
     * @param <D>      The underlying data type.
     * @return The active handler instance ready for SIMULATE/EXECUTE operations, or {@code null} if the requested type/face is not supported.
     */
    @Nullable
    default <F extends IFlux<D>, D> IFluxHandler<F> getFluxHandler(@Nonnull FluxType<F, D> type, @Nonnull BlockFace face, @Nullable String slotName, @Nonnull FluxAccess access) {
        return null;
    }

    /**
     * Retrieves the authoritative handler for a specific Flux resource type, routed by a specific entity model part.
     * <p>
     * This method acts as the entity/complex-model counterpart to the {@link BlockFace} routing.
     * It utilizes the hit details generated by the engine's raycast against custom model bones or hitboxes.
     * </p>
     * <p>
     * <b>LIFECYCLE WARNING:</b> Similar to the face-based query, callers should NEVER cache the returned handler.
     * </p>
     *
     * @param type     The architectural type of the resource requested.
     * @param detail   The specific hit detail, model part, or bone name being accessed (e.g., "fuel_tank_cap").
     *                 Must not be null. Pass an empty string if no specific part was targeted.
     * @param slotName An optional specific slot identifier (e.g., "water_in") to target a named container,
     *                 or {@code null} to query the default un-filtered handler.
     * @param access   The intended operation (FILL or DRAIN) the caller wishes to perform.
     *                 STRICTLY NON-NULL.
     * @param <F>      The carrier payload type.
     * @param <D>      The underlying data type.
     * @return The active handler instance ready for SIMULATE/EXECUTE operations, or {@code null} if the requested type/part is not supported.
     */
    @Nullable
    default <F extends IFlux<D>, D> IFluxHandler<F> getFluxHandler(@Nonnull FluxType<F, D> type, @Nonnull String detail, @Nullable String slotName, @Nonnull FluxAccess access) {
        return null;
    }

    /**
     * Defines the operational intent of a network connection or query.
     * <p>
     * Used by providers to determine if a physical or logical connection should be permitted based on the caller's objective.
     * </p>
     */
    enum FluxAccess {
        FILL,
        DRAIN;

        public boolean fill() {
            return this == FILL;
        }

        public boolean drain() {
            return this == DRAIN;
        }
    }
}
